using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace ConsoleApp1
{
    class MenuDec
    {
        public int optn { get; set; }
        public int Health { get; set; }
        public int Stamina { get; set; }
        public int Hunger { get; set; }
        public int CrntChptr { get; set; }
        public int ChrctrClass { get; set; }
        public string filePath = Directory.GetCurrentDirectory();
        public void Made()
        {
            string fullPath = filePath + "\\" + "Adventurer.txt";
            using (var stream = File.Open(fullPath, FileMode.Create))
            { }

            using (System.IO.StreamWriter file = new System.IO.StreamWriter(fullPath, true))
            {
                file.WriteLine("DO NOT EDIT THIS FILE UNLESS YOU WANT TO CHEAT");
                // line 2
                file.WriteLine(Health);
                // line 3
                file.WriteLine(Stamina);
                // line 4
                file.WriteLine(Hunger);
                file.WriteLine("Current chapter: ");
                // line 6
                file.WriteLine(CrntChptr);
                file.WriteLine("Class: ");
                //line 8
                file.WriteLine(ChrctrClass);
            }



        }
    }
}
